### ISSUE TITLE
how to run on multi-table CardEst, such as imdb

### ISSUE THREAD

**Issue by xchuwenbo** [wuziniu/FSPN#1]
Thanks for you excllent work! Is there any implementation for multi-table CardEst, such as imdb-job-light? I note that some results can be found in https://vldb.org/pvldb/vol14/p1489-zhu.pdf. Thanks!

**Comment by wuziniu** [comment]
Thanks for your interest. Unfortunately, due to the company regulation, I was not able to open-source the multi-table part of this work.

**Comment by xchuwenbo** [comment]
thanks for kindly let me know.
